# Data Columns to use
data_cols = [
"acc_now_delinq"
,"acc_open_past_24mths"
,"addr_state"
,"all_util"
,"annual_inc"
#,"annual_inc_joint"
,"application_type"
,"avg_cur_bal"
,"bc_open_to_buy"
,"bc_util"
,"chargeoff_within_12_mths"
#,"collection_recovery_fee"
,"collections_12_mths_ex_med"
,"delinq_2yrs"
,"delinq_amnt"
#,"desc"
,"dti"
#,"dti_joint"
#,"earliest_cr_line"
,"emp_length"
#,"emp_title"
#,"fico_range_high"
#,"fico_range_low"
,"funded_amnt"
#,"funded_amnt_inv"
,"grade"
,"home_ownership"
#,"id"
,"il_util"
#,"initial_list_status"
,"inq_fi"
,"inq_last_12m"
,"inq_last_6mths"
#,"installment"
,"int_rate"
#,"issue_d"
#,"last_credit_pull_d"
#,"last_fico_range_high"
#,"last_fico_range_low"
#,"last_pymnt_amnt"
#,"last_pymnt_d"
,"loan_amnt"
,"loan_status"
,"max_bal_bc"
#,"member_id"
# ,"mo_sin_old_il_acct"
# ,"mo_sin_old_rev_tl_op"
# ,"mo_sin_rcnt_rev_tl_op"
# ,"mo_sin_rcnt_tl"
# ,"mort_acc"
# ,"mths_since_last_delinq"
# ,"mths_since_last_major_derog"
# ,"mths_since_last_record"
# ,"mths_since_rcnt_il"
# ,"mths_since_recent_bc"
# ,"mths_since_recent_bc_dlq"
# ,"mths_since_recent_inq"
# ,"mths_since_recent_revol_delinq"
#,"next_pymnt_d"
,"num_accts_ever_120_pd"
,"num_actv_bc_tl"
,"num_actv_rev_tl"
,"num_bc_sats"
,"num_bc_tl"
,"num_il_tl"
,"num_op_rev_tl"
,"num_rev_accts"
,"num_rev_tl_bal_gt_0"
,"num_sats"
,"num_tl_120dpd_2m"
,"num_tl_30dpd"
,"num_tl_90g_dpd_24m"
,"num_tl_op_past_12m"
,"open_acc"
,"open_acc_6m"
,"open_il_12m"
,"open_il_24m"
,"open_act_il"
,"open_rv_12m"
,"open_rv_24m"
#,"out_prncp"
#,"out_prncp_inv"
,"pct_tl_nvr_dlq"
,"percent_bc_gt_75"
,"policy_code"
,"pub_rec"
,"pub_rec_bankruptcies"
,"purpose"
#,"pymnt_plan"
#,"recoveries"
,"revol_bal"
,"revol_util"
,"sub_grade"
,"tax_liens"
#,"term"
#,"title"
,"tot_coll_amt"
,"tot_cur_bal"
,"tot_hi_cred_lim"
,"total_acc"
,"total_bal_ex_mort"
,"total_bal_il"
,"total_bc_limit"
,"total_cu_tl"
#,"total_il_high_credit_limit"
#,"total_pymnt"
#,"total_pymnt_inv"
#,"total_rec_int"
#,"total_rec_late_fee"
#,"total_rec_prncp"
,"total_rev_hi_lim"
#,"url"
,"verification_status"
#,"verified_status_joint"
,"zip_code"
#,"revol_bal_joint "
#,"sec_app_fico_range_low "
#,"sec_app_fico_range_high "
#,"sec_app_earliest_cr_line "
#,"sec_app_inq_last_6mths "
#,"sec_app_mort_acc "
#,"sec_app_open_acc "
#,"sec_app_revol_util "
#,"sec_app_open_act_il"
#,"sec_app_num_rev_accts "
#,"sec_app_chargeoff_within_12_mths "
#,"sec_app_collections_12_mths_ex_med "
#,"sec_app_mths_since_last_major_derog "
#,"hardship_flag"
#,"hardship_type"
#,"hardship_reason"
#,"hardship_status"
#,"deferral_term"
#,"hardship_amount"
#,"hardship_start_date"
#,"hardship_end_date"
#,"payment_plan_start_date"
#,"hardship_length"
#,"hardship_dpd"
#,"hardship_loan_status"
#,"orig_projected_additional_accrued_interest"
#,"hardship_payoff_balance_amount"
#,"hardship_last_payment_amount"
#,"disbursement_method"
#,"debt_settlement_flag"
#,"debt_settlement_flag_date"
#,"settlement_status"
#,"settlement_date"
#,"settlement_amount"
#,"settlement_percentage"
#
    ,"settlement_term"
]